CREATE TABLE exam_sessions (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id                   BIGINT       NOT NULL,
    status                    VARCHAR(20)  NOT NULL,
    started_at                TIMESTAMP    NOT NULL,
    ended_at                  TIMESTAMP,
    speed_limit_kmh           INT          NOT NULL,
    score                     INT          NOT NULL,
    critical_infraction_count INT          NOT NULL,
    total_infraction_count    INT          NOT NULL,
    current_speed_kmh         DOUBLE PRECISION NOT NULL,
    last_speed_update_at      TIMESTAMP,
    speeding_since            TIMESTAMP,
    speeding_episode_flagged  BOOLEAN      NOT NULL,
    left_signal_on            BOOLEAN      NOT NULL,
    right_signal_on           BOOLEAN      NOT NULL,
    last_left_signal_on_at    TIMESTAMP,
    last_right_signal_on_at   TIMESTAMP,
    last_client_timestamp     BIGINT,
    version                   BIGINT       NOT NULL,
    CONSTRAINT fk_exam_sessions_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE TABLE exam_events (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id       BIGINT      NOT NULL,
    event_type       VARCHAR(30) NOT NULL,
    direction        VARCHAR(10),
    speed_kmh        DOUBLE PRECISION,
    client_timestamp BIGINT,
    received_at      TIMESTAMP   NOT NULL,
    CONSTRAINT fk_exam_events_session FOREIGN KEY (session_id) REFERENCES exam_sessions (id)
);

CREATE TABLE infractions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id  BIGINT       NOT NULL,
    rule_code   VARCHAR(40)  NOT NULL,
    severity    VARCHAR(10)  NOT NULL,
    message     VARCHAR(255) NOT NULL,
    occurred_at TIMESTAMP    NOT NULL,
    CONSTRAINT fk_infractions_session FOREIGN KEY (session_id) REFERENCES exam_sessions (id)
);

CREATE INDEX idx_exam_sessions_user ON exam_sessions (user_id);
CREATE INDEX idx_exam_events_session ON exam_events (session_id);
CREATE INDEX idx_infractions_session ON infractions (session_id);
